name = "varafx"
main = "src/index.ts"
compatibility_date = "2024-05-29"
account_id = "70911c2a8cdf1844b86156a3b2a2bc3a"

[observability]
enabled = true

[triggers]
crons = ["*/15 * * * *"]

[[kv_namespaces]]
binding = "KV"
id = "bdc3b0f603f84a25958af622f0bf550b"

